# .github/workflows/debug-telegram-secrets.yml
name: Debug Telegram Secrets

# Run this manually via “Actions” → “Debug Telegram Secrets” → “Run workflow”
on:
  workflow_dispatch:

jobs:
  dump-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Write secrets to files
        # Inject the repository secrets into shell environment vars
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Writing TELEGRAM_BOT_TOKEN to telegram-token.txt"
          echo "$TELEGRAM_BOT_TOKEN" > telegram-token.txt

          echo "Writing TELEGRAM_CHAT_ID to telegram-chat-id.txt"
          echo "$TELEGRAM_CHAT_ID" > telegram-chat-id.txt

      - name: Upload debug files
        uses: actions/upload-artifact@v3
        with:
          name: telegram-secrets
          path: |
            telegram-token.txt
            telegram-chat-id.txt
